"""Tests for system-prompt generation and persistence (v3.0.0 B3).

The system prompt is generated by the input generator at run time and stored in
``messages[0]`` — the array is the single source of truth (D1).  These tests
pin the behaviour at the three places it can go wrong: generation, message
placement, and the persistence gate.
"""

from __future__ import annotations

import json
import struct
import zlib
from pathlib import Path
from typing import Any
from unittest.mock import MagicMock

from ard.backends.api_client import (
    ARDEmptyContentError,
    ChatAPIClient,
    ChatAPIStats,
    ChatResponse,
)
from ard.core.system_prompt import SYSTEM_PROMPT_NONE
from ard.core.types import AnchorSpec, DataSource, TurnSpec
from ard.domain.anchor_shape import message_shape_error
from ard.domain.bank import AppendOutcome, append_anchor, read_anchor_bank
from ard.domain.text_anchor import AnchorGenerationStats, generate_text_anchors

SYSTEM_TEXT = "You are a meticulous Python debugger for legacy SQL pipelines."
ANSWER = "The bug is in the join predicate."
REASONING = "Check the join keys, then the filter."


def _spec(mode: str, spec_id: str = "sys_001") -> AnchorSpec:
    """A single-turn spec whose metadata carries *mode*."""
    return AnchorSpec(
        id=spec_id,
        anchor_meta={
            "language": "English",
            "knowledge_domain": "software_engineering",
            "capability": "debugging",
            "conversation_type": "single_turn",
            "system_prompt_mode": mode,
        },
        turns=[
            TurnSpec(
                turn_index=0,
                role="user",
                generation_instruction="Ask about a failing SQL query",
                is_final=True,
            )
        ],
        input_generator_id="input-gen",
    )


def _input_client(system_text: str = SYSTEM_TEXT) -> MagicMock:
    """Input-generator double whose first reply is the system prompt."""
    client = MagicMock(spec=ChatAPIClient)
    client.chat.side_effect = [
        ChatResponse(content=system_text),
        ChatResponse(content="Why does my SQL query return duplicates?"),
    ]
    return client


def _input_client_for_none() -> MagicMock:
    """Input-generator double for a mode-``none`` anchor (one call: the question)."""
    client = MagicMock(spec=ChatAPIClient)
    client.chat.return_value = ChatResponse(content="Why is my query slow?")
    return client


def _target_client() -> MagicMock:
    client = MagicMock(spec=ChatAPIClient)
    client.chat.return_value = ChatResponse(content=ANSWER, reasoning=REASONING)
    return client


def _generate(spec: AnchorSpec, input_client: MagicMock, target_client: MagicMock):
    return generate_text_anchors(
        specs=[spec],
        input_client=input_client,
        target_client=target_client,
        input_model_name="input-model",
        target_model_name="target-model",
        concurrency=1,
        disable_progress=True,
    )


# ── Generation ──────────────────────────────────────────────────────────────


def test_present_mode_prepends_the_generated_system_message() -> None:
    """A styled anchor carries its generated system text at ``messages[0]``."""
    results = _generate(_spec("task_constraint"), _input_client(), _target_client())

    assert len(results) == 1
    messages = results[0].messages
    assert [message["role"] for message in messages] == ["system", "user"]
    assert messages[0]["content"] == SYSTEM_TEXT
    assert message_shape_error(messages) is None


def test_absent_mode_adds_no_system_message() -> None:
    """``none`` behaves exactly like the pre-B3 shape (no system message)."""
    input_client = MagicMock(spec=ChatAPIClient)
    input_client.chat.return_value = ChatResponse(content="Why is my query slow?")

    results = _generate(_spec(SYSTEM_PROMPT_NONE), input_client, _target_client())

    assert len(results) == 1
    messages = results[0].messages
    assert [message["role"] for message in messages] == ["user"]
    # Exactly one input-generator call: no system prompt was requested.
    assert input_client.chat.call_count == 1


def test_system_prompt_is_generated_from_the_anchor_metadata() -> None:
    """The system-prompt request names the anchor's own domain and capability."""
    input_client = _input_client()
    _generate(_spec("domain_style"), input_client, _target_client())

    first_call_messages = input_client.chat.call_args_list[0].args[0]
    prompt_text = "\n".join(message["content"] for message in first_call_messages)
    assert "software_engineering" in prompt_text
    assert "debugging" in prompt_text
    assert "domain-style" in prompt_text


def test_target_model_sees_the_system_message() -> None:
    """The teacher answers with the system prompt in its prefix (scheme §3.3)."""
    target_client = _target_client()
    _generate(_spec("minimal_persona"), _input_client(), target_client)

    messages_sent_to_teacher = target_client.chat.call_args.args[0]
    assert messages_sent_to_teacher[0]["role"] == "system"
    assert messages_sent_to_teacher[0]["content"] == SYSTEM_TEXT


def test_unknown_mode_is_rejected() -> None:
    """An unknown mode is a vocabulary violation, not a silent no-system anchor.

    The scheduler catches per-anchor failures and classifies them
    (:func:`~ard.domain.text_anchor.failure_reason`), so the observable effect
    is an anchor abandoned under ``unexpected_error`` — deliberately *not* one
    of the server/model-output buckets, so a vocabulary bug can never be
    mistaken for load or for a model quirk.
    """
    stats = AnchorGenerationStats()
    results = generate_text_anchors(
        specs=[_spec("casual_vibes")],
        input_client=_input_client(),
        target_client=_target_client(),
        input_model_name="input-model",
        target_model_name="target-model",
        concurrency=1,
        disable_progress=True,
        stats=stats,
    )

    assert results == []
    assert stats.abandoned_by_reason == {"unexpected_error": 1}


def test_empty_system_prompt_abandons_the_anchor() -> None:
    """No system text means no anchor — never a style-less system message."""
    results = _generate(_spec("detailed_persona"), _input_client("   "), _target_client())

    # The empty system prompt is classified as a model-output failure by the
    # scheduler (`failure_reason`), so the run returns no anchor instead of a
    # record that claims a style it does not carry.
    assert results == []


# ── Persistence ─────────────────────────────────────────────────────────────


def test_system_message_survives_the_persistence_gate(tmp_path: Path) -> None:
    """The generated system message is what lands in the bank."""
    results = _generate(_spec("task_constraint"), _input_client(), _target_client())
    anchor = results[0]

    bank = tmp_path / "anchor_bank.jsonl"
    assert append_anchor(anchor, bank) is AppendOutcome.APPENDED

    records = read_anchor_bank(bank)
    assert len(records) == 1
    record = records[0]
    assert [message["role"] for message in record["messages"]] == ["system", "user"]
    assert record["messages"][0]["content"] == SYSTEM_TEXT
    assert "system_prompt" not in record  # D1: messages are the only truth
    assert record["anchor_meta"]["system_prompt_mode"] == "task_constraint"
    assert record["data_source"] == "ard_text"


# ── data_source routing key (per anchor, not per run) ────────────────────────


def test_text_anchor_routes_to_ard_text() -> None:
    """An anchor with no image parts carries the text routing key."""
    results = _generate(_spec(SYSTEM_PROMPT_NONE), _input_client_for_none(), _target_client())
    assert results[0].data_source is DataSource.ARD_TEXT


def test_image_anchor_routes_to_ard_multi(tmp_path: Path) -> None:
    """An anchor whose messages carry an image part carries the multi key."""
    png = _create_minimal_png(tmp_path)
    spec = AnchorSpec(
        id="img_001",
        anchor_meta={
            "language": "English",
            "knowledge_domain": "vision",
            "capability": "qa",
            "conversation_type": "single_turn",
            "system_prompt_mode": SYSTEM_PROMPT_NONE,
        },
        turns=[
            TurnSpec(
                turn_index=0,
                role="user",
                generation_instruction="Describe this image",
                image_path=str(png),
                is_final=True,
            )
        ],
    )
    input_client = MagicMock(spec=ChatAPIClient)
    input_client.chat.return_value = ChatResponse(content="What do you see?")

    results = _generate(spec, input_client, _target_client())

    assert len(results) == 1
    anchor = results[0]
    assert anchor.data_source is DataSource.ARD_MULTI
    # The key describes what the record actually contains.
    assert any(
        isinstance(part, dict) and part.get("type") == "image"
        for message in anchor.messages
        for part in (message["content"] if isinstance(message["content"], list) else [])
    )

    bank = tmp_path / "img_bank.jsonl"
    assert append_anchor(anchor, bank) is AppendOutcome.APPENDED
    assert read_anchor_bank(bank)[0]["data_source"] == "ard_multi"


def test_image_run_without_allocated_image_stays_text() -> None:
    """The key follows the anchor, not the run: an unallocated image turn is text.

    This is the case that makes a run-level flag wrong: ``--image-dir`` was
    passed, but this spec's turn ended up with no image (empty/exhausted pool),
    so the record is text-only and must be routed as such.
    """
    spec = AnchorSpec(
        id="noimg_001",
        anchor_meta={
            "language": "English",
            "knowledge_domain": "vision",
            "capability": "qa",
            "conversation_type": "single_turn",
            "system_prompt_mode": SYSTEM_PROMPT_NONE,
        },
        turns=[TurnSpec(turn_index=0, role="user", is_final=True)],  # no image_path
    )
    input_client = MagicMock(spec=ChatAPIClient)
    input_client.chat.return_value = ChatResponse(content="Why is the sky blue?")

    results = _generate(spec, input_client, _target_client())
    assert results[0].data_source is DataSource.ARD_TEXT


def test_anchor_data_source_reads_image_parts() -> None:
    """Both persisted image forms count; text-only and non-image parts do not.

    Two forms are accepted, and they are accepted for different reasons:

    * ``{"type": "image", "image": "images/x.jpg"}`` — the rewritten form that
      ``_convert_images_to_paths`` writes for every anchor, in the default run
      *and* in a ``--no-convert`` run (that flag only decides whether image
      *files* are transcoded when copied into the output directory; it never
      touches message parts);
    * ``{"type": "image_url", "image_url": {"url": "data:image/jpeg;base64,…"}}``
      — the API's inline form.  It is **not** an expected persisted form: it
      reaches the bank only through a writer bug, and it did reach it once.  It
      is still matched, because the routing rule must describe the *record*
      rather than the writer's current habits — a rule that only accepts today's
      shape goes quiet the moment the writer changes again.

    Missing the second form is what made the B3 verification run label every
    image anchor ``ard_text`` — the inline form was the only one that run
    produced, and the function matched only ``image``.  Missing the *first* form
    is the symmetric failure: those records would be split off as text-only.
    """
    from ard.domain.text_anchor import anchor_data_source

    assert anchor_data_source([{"role": "user", "content": "plain"}]) is DataSource.ARD_TEXT

    assert (
        anchor_data_source(
            [
                {"role": "user", "content": "plain"},
                {
                    "role": "user",
                    "content": [
                        {"type": "image", "image": "images/x.jpg"},
                        {"type": "text", "text": "what is this?"},
                    ],
                },
            ]
        )
        is DataSource.ARD_MULTI
    )
    assert (
        anchor_data_source(
            [
                {
                    "role": "user",
                    "content": [
                        {"type": "image_url", "image_url": {"url": "data:image/jpeg;base64,AAAA"}},
                        {"type": "text", "text": "what is this?"},
                    ],
                }
            ]
        )
        is DataSource.ARD_MULTI
    )
    # A text-only part list stays text, even though it is a list.
    assert (
        anchor_data_source(
            [{"role": "user", "content": [{"type": "text", "text": "no image here"}]}]
        )
        is DataSource.ARD_TEXT
    )


# ── Image handling end-to-end (real conversion path, leading system included) ─
#
# The tests above pin the routing *function*; the three below pin the *pipeline*,
# because these are the two paths that a green unit test cannot vouch for.  An
# earlier version of this file covered the inline form by patching
# ``_convert_images_to_paths`` into an identity function, which is the one thing
# that must never be done here: the patch *manufactured* the inline form the test
# then asserted, so it stayed green while the real pipeline kept base64 in every
# anchor that carried a system prompt.  These tests therefore run the unpatched
# pipeline and assert on what the bank would actually contain.


def _image_spec_meta(mode: str) -> dict[str, str]:
    """Anchor metadata for a single-turn image anchor in the given mode."""
    return {
        "language": "English",
        "knowledge_domain": "vision",
        "capability": "qa",
        "conversation_type": "single_turn",
        "system_prompt_mode": mode,
    }


def test_no_convert_run_routes_image_anchor_to_ard_multi(tmp_path: Path) -> None:
    """Legacy inline records still route to ``ard_multi`` (no conversion run).

    ``_convert_images_to_paths`` is not called at all here, which is the closest
    local stand-in for a run whose conversion step is bypassed — the state that
    produced the pre-fix inline records.  The point is the routing rule, not the
    conversion: such a record plainly carries an image and must not be filed as
    text-only (W-1 / §1.4).

    Note the asymmetry with the end-to-end test below: **this input can no longer
    be produced by the pipeline itself.**  It is kept as a guard for records
    written before the alignment fix.
    """
    from ard.domain.text_anchor import _convert_images_to_paths

    images_dir = tmp_path / "images"
    images_dir.mkdir()
    png = _create_minimal_png(images_dir)
    inline: dict[str, Any] = {
        "role": "user",
        "content": [
            {"type": "text", "text": "What do you see?"},
            {"type": "image_url", "image_url": {"url": "data:image/jpeg;base64,AAAA"}},
        ],
    }
    spec = AnchorSpec(
        id="img_nowriter",
        anchor_meta=_image_spec_meta(SYSTEM_PROMPT_NONE),
        turns=[
            TurnSpec(
                turn_index=0,
                role="user",
                generation_instruction="Describe this image",
                image_path=str(png),
                is_final=True,
            )
        ],
    )

    # The pre-fix record shape, built by hand instead of by patching the helper:
    # converting it would rewrite the part, so the inline form only survives if
    # the conversion step is not run at all.
    passed_through = [inline]
    assert passed_through[0]["content"][1]["type"] == "image_url"
    assert _convert_images_to_paths(passed_through, spec)[0]["content"][1] == {
        "type": "image",
        "image": "images/probe.png",
    }, "the helper must rewrite image_url parts into the referenced-path form"

    from ard.domain.text_anchor import anchor_data_source

    assert anchor_data_source(passed_through) is DataSource.ARD_MULTI

    results = _generate(spec, _input_client_for_none(), _target_client())
    assert len(results) == 1
    anchor = results[0]

    # By the time a real run persists its anchor, the inline form is gone: the
    # turn that owns the image is matched through the leading-system offset.
    persisted_types = [
        part.get("type")
        for message in anchor.messages
        for part in (message["content"] if isinstance(message["content"], list) else [])
    ]
    assert "image_url" not in persisted_types, persisted_types
    assert "image" in persisted_types, persisted_types
    assert anchor.data_source is DataSource.ARD_MULTI

    bank = tmp_path / "noinline_bank.jsonl"
    assert append_anchor(anchor, bank) is AppendOutcome.APPENDED
    assert read_anchor_bank(bank)[0]["data_source"] == "ard_multi"


def test_pipeline_with_system_prompt_converts_image_to_a_path(tmp_path: Path) -> None:
    """A leading ``system`` message must not stop the image from being rewritten.

    This is the regression test for the alignment defect: message *i* was paired
    with ``spec.turns[i]``, so once the generated system prompt occupied
    ``messages[0]``, the image-owning turn 0 was looked up as ``turns[1]`` — a
    turn without an ``image_path`` — and the rewrite was skipped.  Every anchor
    with a system prompt (i.e. the whole B3 feature) therefore persisted its
    image as an inline base64 data URI, which also contradicted
    ``test_integration.py``'s ``assert "image_url" not in json.dumps(messages)``.

    The system message is real here (``task_constraint`` mode, generated by the
    input-generator double), so the offset exists exactly as it does in a run.
    """
    images_dir = tmp_path / "images"
    images_dir.mkdir()
    png = _create_minimal_png(images_dir)
    spec = AnchorSpec(
        id="img_with_system",
        anchor_meta=_image_spec_meta("task_constraint"),
        turns=[
            TurnSpec(
                turn_index=0,
                role="user",
                generation_instruction="Describe this image",
                image_path=str(png),
                is_final=True,
            )
        ],
    )
    input_client = _input_client()  # first call = the system prompt, then the question

    results = _generate(spec, input_client, _target_client())

    assert len(results) == 1
    anchor = results[0]
    assert [m["role"] for m in anchor.messages] == ["system", "user"]

    persisted_types = [
        part.get("type")
        for message in anchor.messages
        for part in (message["content"] if isinstance(message["content"], list) else [])
    ]
    assert "image" in persisted_types, persisted_types
    assert "image_url" not in persisted_types, persisted_types
    assert "base64" not in json.dumps(anchor.messages)
    assert anchor.data_source is DataSource.ARD_MULTI

    bank = tmp_path / "sys_image_bank.jsonl"
    assert append_anchor(anchor, bank) is AppendOutcome.APPENDED
    record = read_anchor_bank(bank)[0]
    assert record["data_source"] == "ard_multi"

    image_paths = [
        part["image"]
        for message in record["messages"]
        for part in (message["content"] if isinstance(message["content"], list) else [])
        if isinstance(part, dict) and part.get("type") == "image"
    ]
    assert image_paths == ["images/probe.png"], image_paths


def test_multiturn_image_paths_stay_aligned_behind_a_system_prompt(tmp_path: Path) -> None:
    """Two images on two turns each keep *their own* path with a system prompt.

    ``test_integration.py::test_image_paths_stay_aligned_with_their_turns``
    guards the same invariant without a system prompt, which is exactly why the
    offset defect slipped past it: its spec never has a ``system_prompt_mode``,
    so the 1:1 assumption held.  With the leading system in place, a fix that
    shifted the pairing instead of removing it would swap the two paths — this
    test fails on that, not just on a leaked base64.
    """
    images_dir = tmp_path / "images"
    images_dir.mkdir()
    first = _create_minimal_png(images_dir, "first.png")
    second = _create_minimal_png(images_dir, "second.png")

    spec = AnchorSpec(
        id="img_alignment_system",
        anchor_meta={
            "language": "English",
            "knowledge_domain": "vision",
            "capability": "description",
            "conversation_type": "multi_turn",
            "system_prompt_mode": "minimal_persona",
        },
        turns=[
            TurnSpec(
                turn_index=0,
                role="user",
                generation_instruction="Describe this image",
                image_path=str(first),
            ),
            TurnSpec(turn_index=1, role="assistant", generation_instruction="Respond"),
            TurnSpec(
                turn_index=2,
                role="user",
                generation_instruction="And this one?",
                image_path=str(second),
                is_final=True,
            ),
        ],
        input_generator_id="input-gen",
    )

    input_client = MagicMock(spec=ChatAPIClient)
    input_client.chat.side_effect = [
        ChatResponse(content=SYSTEM_TEXT),  # the system prompt (messages[0])
        ChatResponse(content="What is in this image?"),
        ChatResponse(content="What about this one?"),
    ]

    results = _generate(spec, input_client, _target_client())

    assert len(results) == 1
    anchor = results[0]
    assert [m["role"] for m in anchor.messages] == ["system", "user", "assistant", "user"]

    def image_parts(message: dict) -> list[str]:
        content = message["content"]
        if not isinstance(content, list):
            return []
        return [
            part["image"]
            for part in content
            if isinstance(part, dict) and part.get("type") == "image"
        ]

    assert image_parts(anchor.messages[0]) == []  # the system message has no image
    assert image_parts(anchor.messages[1]) == ["images/first.png"]
    assert image_parts(anchor.messages[2]) == []
    assert image_parts(anchor.messages[3]) == ["images/second.png"]
    assert "base64" not in json.dumps(anchor.messages)
    assert anchor.data_source is DataSource.ARD_MULTI


def test_misplaced_system_message_is_refused(tmp_path: Path) -> None:
    """Failure path: an anchor with a trailing system message is not written.

    The anchor is produced by the real generation path (with a system prompt),
    so the record that reaches the gate is the one the pipeline builds; it is
    only the *placement* that is corrupted, which is the failure the shape
    contract exists to catch.
    """
    results = _generate(_spec("minimal_persona"), _input_client(), _target_client())
    assert len(results) == 1
    anchor = results[0]
    anchor.messages.append({"role": "system", "content": "late system"})

    bank = tmp_path / "anchor_bank.jsonl"
    assert append_anchor(anchor, bank) is AppendOutcome.INVALID_SHAPE_SKIPPED
    assert not bank.exists()


def test_off_vocabulary_data_source_is_refused(tmp_path: Path) -> None:
    """Failure path: a record no consumer can route is not written (W-1)."""
    anchor = _manual_anchor()
    # Bypass the enum on purpose: the exit gate must refuse the value even when
    # it arrives from code that did not go through the dataclass annotation.
    object.__setattr__(anchor, "data_source", "ard_txt")

    bank = tmp_path / "anchor_bank.jsonl"
    assert append_anchor(anchor, bank) is AppendOutcome.INVALID_DATA_SOURCE_SKIPPED
    assert not bank.exists()


def _manual_anchor():
    from ard.core.types import GeneratedAnchor

    return GeneratedAnchor(
        id="manual_001",
        messages=[{"role": "user", "content": "hello"}],
        target_answer="hi",
        target_model="target-model",
        input_generator_model="input-model",
        anchor_meta={},
    )


def test_data_source_default_is_text() -> None:
    """A newly built anchor is routable without any explicit argument."""
    from ard.core.types import GeneratedAnchor

    anchor = GeneratedAnchor(
        id="default_001",
        messages=[{"role": "user", "content": "hello"}],
        target_answer="hi",
        target_model="target-model",
        input_generator_model="input-model",
        anchor_meta={},
    )
    assert anchor.data_source is DataSource.ARD_TEXT
    assert json.loads(json.dumps({"data_source": anchor.data_source.value})) == {
        "data_source": "ard_text"
    }


def _create_minimal_png(directory: Path, name: str = "probe.png") -> Path:
    """Write a minimal 1x1 red PNG and return its path."""

    def _chunk(chunk_type: bytes, data: bytes) -> bytes:
        payload = chunk_type + data
        crc = struct.pack(">I", zlib.crc32(payload) & 0xFFFFFFFF)
        return struct.pack(">I", len(data)) + payload + crc

    png = (
        b"\x89PNG\r\n\x1a\n"
        + _chunk(b"IHDR", struct.pack(">IIBBBBB", 1, 1, 8, 2, 0, 0, 0))
        + _chunk(b"IDAT", zlib.compress(b"\x00\xff\x00\x00"))
        + _chunk(b"IEND", b"")
    )
    path = directory / name
    path.write_bytes(png)
    return path


def test_empty_system_message_error_carries_stats() -> None:
    """The empty-system-prompt failure is an ARDEmptyContentError with stats."""
    error = ARDEmptyContentError("no text", ChatAPIStats())
    assert error.reason == "no text"
